### PR TITLE
Updated django.core to django.urls to be compatible with django 2.2

### PR DESCRIPTION
**Pull request by CSprat451**

### CODE REVIEW

**Comment by nolsto** [comment]
Does this actually do what is expected?
`get_resolver` and the former `urlresolvers.set_urlconf` were doing fundamentally different things.

`set_urlconf` takes the urlconf name and overrides the default urlconf (from settings) for the current thread.
`get_resolver` simply returns a resolver (the thing used to resolve URLs given a urlconf). The call changes nothing about the thread and is basically a no-op since it doesn't do anything with the resolver.

**Comment by nolsto** [comment]
I think this change will break some templates rendered by views that have a custom urlconf (set by a middleware most likely). If the template uses a `url` tag to reverse a url that can only be found via the custom urlconf, it will result in a`NoReverseMatch` exception being raised.

**Comment by nolsto** [comment]
I think the problem the try/finally block is trying to solve is no longer an issue in [Django 1.11+](https://github.com/django/django/blob/stable/1.11.x/django/core/handlers/base.py) using the new Middleware structure. If we were actually doing a full upgrade and removing Django < 2.2 support, we could remove this precaution. Just putting that as a note here.

**Comment by CSprat451** [comment]
I'm happy to keep upgrading other parts of django-gtf if that's what we want to do. I was keeping it simple and only changing the part that was causing an issue.

**Review by nolsto — APPROVED** [review]

**Pull request merged**
